name: "[Go-Harbor-Matrix] Gin Project Build & Push Multi-Arch"

on:
  push:
    paths:
      - go/**
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  REGISTRY: ${{ secrets.HARBOR_REGISTRY }}
  IMAGE:    ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/${{ secrets.HARBOR_REPO }}

jobs:
# ──────────────────────────────────────────
# 1) 플랫폼별 이미지 Build & Push
# ──────────────────────────────────────────
  build-and-push:
    name: Build & Push (${{ matrix.arch }})
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v3

    - uses: docker/setup-buildx-action@v3

    # Harbor 로그인
    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    # 버전 태그
    - name: Set version tag
      id: ver
      run: echo "VER=$((GITHUB_RUN_NUMBER-1))" >> "$GITHUB_OUTPUT"

    # 플랫폼별 Child 이미지 푸시
    - name: Build & push image (${{ matrix.arch }})
      uses: docker/build-push-action@v5
      with:
        context: ./go
        file:    ./go/Dockerfile
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: ${{ env.IMAGE }}:go-${{ matrix.arch }}-v${{ steps.ver.outputs.VER }}

# ──────────────────────────────────────────
# 2) 통합 Manifest 생성
# ──────────────────────────────────────────
  create-manifest:
    name: Create & Push Multi‑Arch Manifest
    needs: build-and-push
    runs-on: ubuntu-24.04

    steps:
    - name: Set version tag
      id: ver
      run: echo "VER=$((GITHUB_RUN_NUMBER-1))" >> "$GITHUB_OUTPUT"

    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Create & push manifest
      run: |
        docker buildx imagetools create \
          --tag ${IMAGE}:go-latest \
          --tag ${IMAGE}:go-v${{ steps.ver.outputs.VER }} \
          ${IMAGE}:go-amd64-v${{ steps.ver.outputs.VER }} \
          ${IMAGE}:go-arm64-v${{ steps.ver.outputs.VER }}
