name: "[React] Development Branch Test Action"

on:
  push:
    paths:
      - react/**
    branches-ignore:
      - main
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy
        run: echo "Deploying ..."
