name: Test Project # Action의 이름

# 트리거를 정의
# push: 특정 브랜치에 코드가 푸시될 때 워크플로우를 실행
# pull_request: 특정 브랜치에 PR(pull request)이 생성되거나 업데이트될 때 실행
# schedule: 크론 스케줄을 사용하여 정기적으로 실행
# workflow_dispatch: 수동으로 실행할 수 있는 버튼을 추가하여 실행
on: push 

jobs: # 작업 단위
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code # 코드를 가져오는 step
        uses: actions/checkout@v3 # 특정 액션이나 재사용 가능한 코드를 가져와 실행할 때 사용하는 키워드
      # node js는 ubuntu 환경에 이미 존재하지만 학습상 진행
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # CI/CD 및 일관된 종속성 설치에 특화된 패키지 설치방법
      - name: Run test
        run: npm test
